name: Auto Build Artifacts for Refactor/Boxy
on:
  push:
    branches: [ "refactor/boxy" ]
  pull_request:
    branches: [ "refactor/boxy" ]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-20.04, windows-latest ]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install YARN
        run: npm i -g yarn

      - name: Install frontend dependencies
        run: yarn --no-frozen-lockfile

      - name: Build tauri app
        uses: tauri-apps/tauri-action@v0

      - name: Upload Artifact (Windows)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: BlockScripter-DEV-windows
          path: src-tauri/target/release/*.exe


      - name: Upload Artifact (MacOS)
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: BlockScripter-DEV-macos
          path: src-tauri/target/release/bundle/dmg/*.dmg


      - name: Upload Artifact (Ubuntu)
        if: matrix.platform == 'ubuntu-20.04'
        uses: actions/upload-artifact@v4
        with:
          name: BlockScripter-DEV-linux
          path: src-tauri/target/release/bundle/deb/*.deb
